"""Fixtures were generated by the original v1 core from commit 1e3026a."""
from pathlib import Path
import pytest
import png_steg_aes256 as core

FIXTURES = Path(__file__).parent / 'fixtures'
DATA = b'Legacy v1 synthetic compatibility payload\n' * 8


@pytest.mark.parametrize('extension', ['png', 'saes'])
def test_original_v1_container_still_authenticates(extension):
    credential = core.Credential.from_password('legacy fixture password')
    decode = core.decode_image if extension == 'png' else core.decode_encrypted_file
    decoded = decode(FIXTURES / ('legacy-v1.' + extension), credential=credential)
    assert decoded.filename == 'legacy.txt'
    assert decoded.data == DATA


def test_legacy_posix_name_requires_explicit_safe_restore(tmp_path, monkeypatch):
    credential = core.Credential.from_password('legacy fixture password')
    container = FIXTURES / 'legacy-posix-name.saes'
    assert core.decode_encrypted_file(container, credential=credential).filename == 'file:note.txt'
    monkeypatch.chdir(tmp_path)
    with pytest.raises(core.StegError):
        core.decrypt_encrypted_file(container, None, credential=credential)
    assert not list(tmp_path.iterdir())
    output = tmp_path / 'safe-name.txt'
    core.decrypt_encrypted_file(container, output, credential=credential)
    assert output.read_bytes() == DATA
